import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import { ThemeProvider } from "@/providers/theme";
import { cn } from "@/lib/utils";
import Header from "@/components/header/header";
import "./globals.css";
import { BookingProvider } from "@/context/bus-ticket";
import { AuthProvider } from "@/providers/auth";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/footer/footer";

const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Machu Picchu Bus Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={cn("antialiased", instrumentSans.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <BookingProvider>
              <Header />
              {children}
              <Footer />
              <Toaster position="top-center" richColors />
            </BookingProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
